# Generated by Django 3.0.5 on 2020-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanswers',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
