# Generated by Django 3.0.5 on 2020-11-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('application_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_guardian', models.CharField(blank=True, max_length=100, null=True)),
                ('house_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('marriage_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.PhoneNumberStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerFieldReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('marriage_date', models.DateTimeField(blank=True, null=True)),
                ('financial_bg', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('gold_amt', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage_set', models.CharField(blank=True, max_length=10, null=True)),
                ('is_exchanging', models.BooleanField(blank=True, default=False, null=True)),
                ('is_exchanging_old', models.BooleanField(blank=True, default=False, null=True)),
                ('is_taking_emi', models.BooleanField(blank=True, default=False, null=True)),
                ('duraton_of_loan', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_emi', models.IntegerField(blank=True, default=0, null=True)),
                ('is_advance_booking', models.BooleanField(blank=True, default=False, null=True)),
                ('token_advance', models.CharField(blank=True, max_length=10, null=True)),
                ('rate_at_booking', models.CharField(blank=True, max_length=10, null=True)),
                ('is_another_jeweller_came', models.BooleanField(blank=True, default=False, null=True)),
                ('is_advanced_in_other', models.BooleanField(blank=True, default=False, null=True)),
                ('amount_advanced_in_other', models.CharField(blank=True, max_length=10, null=True)),
                ('know_any_new_party', models.BooleanField(blank=True, default=False, null=True)),
                ('no_of_party', models.IntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
