# Generated by Django 3.0.5 on 2020-12-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_area_company'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerfieldreport',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
