# Generated by Django 3.0.5 on 2020-12-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201203_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfieldagent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Updation')], default=1),
        ),
    ]
