# Generated by Django 3.0.5 on 2020-12-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerfieldagent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='application_no',
        ),
    ]
