# Generated by Django 3.0.5 on 2020-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_application_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
