# Generated by Django 3.0.5 on 2020-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201203_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerphonenumber',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerfieldagent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Edited')], default=1),
        ),
    ]
