# Generated by Django 3.0.5 on 2020-12-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201203_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerphonenumber',
            name='is_invalid',
        ),
    ]
