# Generated by Django 3.0.5 on 2020-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customerphonenumber_is_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfieldreport',
            name='image_1',
            field=models.ImageField(default=1, upload_to='field_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfieldreport',
            name='image_2',
            field=models.ImageField(default='1', upload_to='field_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfieldreport',
            name='image_3',
            field=models.ImageField(default='1', upload_to='field_image/'),
            preserve_default=False,
        ),
    ]
