# Generated by Django 3.0.5 on 2020-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20201204_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfieldreport',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='field_image/'),
        ),
        migrations.AlterField(
            model_name='customerfieldreport',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='field_image/'),
        ),
        migrations.AlterField(
            model_name='customerfieldreport',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='field_image/'),
        ),
    ]
