# Generated by Django 3.0.5 on 2020-12-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20201210_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfieldreport',
            name='gold_amt_exchanging',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
