# Generated by Django 3.0.5 on 2020-12-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerfieldreport_gold_amt_exchanging'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfieldreport',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerfieldreport',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerfieldreport',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
