# Generated by Django 3.0.5 on 2021-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customerwithfieldreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwithfieldreport',
            name='last_call_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
