# Generated by Django 3.0.5 on 2021-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20210201_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='month',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
