# Generated by Django 3.0.5 on 2020-10-26 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentphonenumber',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='agentphonenumber',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.PhoneNumberStatus'),
        ),
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.Area'),
        ),
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.Group'),
        ),
    ]
