# Generated by Django 3.0.5 on 2020-12-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20201130_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='company',
        ),
    ]
