# Generated by Django 3.0.5 on 2020-12-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_area_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactstatus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.RemoveField(
            model_name='phonenumberstatus',
            name='company',
        ),
    ]
