# Generated by Django 3.0.5 on 2020-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20201203_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberstatus',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
