# Generated by Django 3.0.5 on 2021-01-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_phonenumberstatus_is_invalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
